platform :ios, '9.0'

use_frameworks!

target 'Analytical_Example' do
  pod 'Analytical', :path => '../'
  
  pod 'Google/Analytics'

  target 'Analytical_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
