platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

target 'Analytical_Example' do
  pod 'Analytical', :path => '../'
  pod 'Google/Analytics'

  target 'Analytical_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
  end
end
